# Generated by Django 3.1.7 on 2021-03-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.TextField(verbose_name='в каком клубе')),
                ('date_start', models.DateTimeField(verbose_name='начало акции')),
                ('date_end', models.DateTimeField(verbose_name='конец акции')),
                ('how_open', models.TextField(verbose_name='как открыть коробку')),
                ('about_text', models.TextField(verbose_name='о кейсах')),
            ],
            options={
                'verbose_name': 'кейс',
                'verbose_name_plural': 'кейсы',
            },
        ),
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.TextField(verbose_name='техническое название')),
                ('text_name', models.TextField(verbose_name='название клуба')),
                ('address', models.TextField(verbose_name='адрес клуба')),
                ('telegram_token', models.TextField(verbose_name='telegram токен')),
            ],
            options={
                'verbose_name': 'клуб',
                'verbose_name_plural': 'клубы',
            },
        ),
        migrations.CreateModel(
            name='FullInfoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='id в клубе')),
                ('user_club', models.TextField(verbose_name='из какого клуба')),
                ('nickname', models.TextField(verbose_name='имя пользователя')),
                ('telegram_id', models.TextField(verbose_name='telegram id')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Mainlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorddtime', models.DateTimeField(auto_now_add=True, verbose_name='дата записи')),
                ('cashadd', models.FloatField(verbose_name='размер платежа')),
                ('clientid', models.IntegerField(unique=True, verbose_name='id клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='внешний ID')),
                ('name', models.TextField(verbose_name='имя пользователя')),
                ('balance', models.FloatField(default=0, verbose_name='баланс')),
                ('open_day', models.PositiveIntegerField(default=0, verbose_name='день открытия')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время получения')),
                ('text', models.CharField(max_length=100, verbose_name='награда')),
                ('is_received', models.BooleanField(default=False, verbose_name='получил')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.profile', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время отправки')),
                ('value', models.FloatField(verbose_name='размер платежа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
