# Generated by Django 3.1.7 on 2021-03-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='внешний ID')),
                ('name', models.TextField(verbose_name='имя пользователя')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время отправки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'сообщения',
            },
        ),
    ]
