# Generated by Django 3.1.7 on 2021-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210326_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainlog',
            options={'verbose_name': 'логи', 'verbose_name_plural': 'логи'},
        ),
        migrations.AlterField(
            model_name='mainlog',
            name='clientid',
            field=models.IntegerField(verbose_name='id клиента'),
        ),
    ]
