# Generated by Django 3.1.7 on 2021-03-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_profile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_today',
            field=models.PositiveIntegerField(default=0, verbose_name='открыл сегодня'),
        ),
    ]
