# Generated by Django 3.1.7 on 2021-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_profile_open_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_day',
            field=models.PositiveIntegerField(default=0, verbose_name='день открытия'),
        ),
    ]
