# Generated by Django 3.1.7 on 2021-03-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_profile_open_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='open_today',
        ),
    ]
