# Generated by Django 3.1.7 on 2021-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210328_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.TextField(default='', verbose_name='в каком клубе')),
                ('cost', models.CharField(default='', max_length=8, verbose_name='цена кейса')),
            ],
            options={
                'verbose_name': 'цена кейса',
                'verbose_name_plural': 'цены кейсов',
            },
        ),
    ]
