# Generated by Django 3.1.7 on 2021-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_casescost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.TextField(default='', verbose_name='в каком клубе')),
                ('cost', models.CharField(default='', max_length=8, verbose_name='цена кейса')),
                ('text', models.CharField(default='', max_length=100, verbose_name='награда')),
            ],
            options={
                'verbose_name': 'список наград',
                'verbose_name_plural': 'список наград',
            },
        ),
    ]
