# Generated by Django 3.1.7 on 2021-03-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_profile_open_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время получения')),
                ('text', models.CharField(max_length=100, verbose_name='награда')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.profile', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
            },
        ),
    ]
