# Generated by Django 3.1.7 on 2021-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='получил'),
        ),
    ]
