# Generated by Django 3.1.7 on 2021-03-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_caserewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebody',
            name='message_text',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='о кейсах'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='club',
            field=models.TextField(default='goodgame', null=True, verbose_name='в каком клубе'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец акции'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало акции'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='how_open',
            field=models.TextField(blank=True, null=True, verbose_name='как открыть коробку'),
        ),
        migrations.AlterField(
            model_name='casebody',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cases/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='casescost',
            name='club',
            field=models.TextField(blank=True, null=True, verbose_name='в каком клубе'),
        ),
        migrations.AlterField(
            model_name='casescost',
            name='cost',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='цена кейса'),
        ),
    ]
