# Generated by Django 3.1.7 on 2021-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210328_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casegrades',
            options={'verbose_name': 'настройка кейса', 'verbose_name_plural': 'настройки кейсов'},
        ),
        migrations.AlterField(
            model_name='casegrades',
            name='club',
            field=models.TextField(blank=True, default='goodgame', null=True, verbose_name='в каком клубе'),
        ),
    ]
