# Generated by Django 3.1.7 on 2021-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210328_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casegrades',
            options={'verbose_name': 'настройка кейса', 'verbose_name_plural': 'настройка кейсов'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='profile',
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='адрес клуба'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='id_name',
            field=models.TextField(default='goodgame', null=True, verbose_name='техническое название'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='telegram_token',
            field=models.TextField(blank=True, null=True, verbose_name='telegram токен'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='text_name',
            field=models.TextField(blank=True, null=True, verbose_name='название клуба'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
