# Generated by Django 3.1.7 on 2021-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.TextField(blank=True, null=True, verbose_name='id клуба')),
                ('user_id', models.TextField(blank=True, null=True, verbose_name='владелец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время получения')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='награда')),
                ('is_received', models.BooleanField(default=False, verbose_name='получил')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
            },
        ),
        migrations.DeleteModel(
            name='CaseRewards',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
