# Generated by Django 3.1.7 on 2021-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210328_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casereward',
            options={'verbose_name': 'награда пользователя', 'verbose_name_plural': 'награды пользователей'},
        ),
    ]
