# Generated by Django 3.1.7 on 2021-03-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210328_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casereward',
            old_name='club_id',
            new_name='club',
        ),
        migrations.AlterField(
            model_name='casegrades',
            name='rewards',
            field=models.TextField(blank=True, null=True, verbose_name='призы через запятую с пробелом'),
        ),
    ]
