# Generated by Django 3.1.7 on 2021-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210328_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegrades',
            name='weights',
            field=models.TextField(blank=True, null=True, verbose_name='веса через запятую с пробелом'),
        ),
    ]
