# Generated by Django 3.1.7 on 2021-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_casegrades_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereward',
            name='case_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='из какого кейса'),
        ),
    ]
