# Generated by Django 3.1.7 on 2021-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_casereward_case_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegrades',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=3, verbose_name='лимит кейсов в день'),
        ),
    ]
