# Generated by Django 3.1.7 on 2021-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_casegrades_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casegrades',
            name='limit',
        ),
        migrations.AddField(
            model_name='casebody',
            name='limit',
            field=models.PositiveIntegerField(blank=True, default=3, verbose_name='лимит кейсов в день'),
        ),
    ]
